[package]
name = "gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
pollster = "0.4.0"
wgpu = "24.0.1"
winit = "0.30.9"
bytemuck = { version = "1.21.0", features = ["derive"] }
env_logger = "0.11.6"
